app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/',
         auth_views.LoginView.as_view(template_name='app/login.html'),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('product/<int:product_id>/', views.detail, name='detail'),
    path('fav_products/', views.fav_products, name='fav_products'),
    path('toggle_fav_product_status/', views.toggle_fav_product_status, name='toggle_fav_product_status'),
]

ecsite2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

# 投稿した画像を表示するための設定、解説は 4.3 を参照 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth import get_user_model

class Product(models.Model): 

    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    price = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='product')

    def __str__(self):
       return self.name

class Sale(models.Model): 

    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    user = models.ForeignKey('users.User', on_delete=models.PROTECT)
    amount = models.PositiveIntegerField(default=0)
    price = models.PositiveIntegerField("商品単価")
    total_price = models.PositiveIntegerField("小計")
    created_at = models.DateTimeField(auto_now=True)

users/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.core.mail import send_mail
from django.utils import timezone
from django.contrib.auth.base_user import BaseUserManager
from app.models import Product 

class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields): 
            if not email:
                raise ValueError('The given email must be set') 

            email = self.normalize_email(email)
            user = self.model(email=email, **extra_fields) 
            user.set_password(password) 
            user.save(using=self.db)
            return user

    def create_user(self, email, password=None, **extra_fields):
            extra_fields.setdefault('is_staff', False)
            extra_fields.setdefault('is_superuser', False)
            return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
            extra_fields.setdefault('is_staff', True)
            extra_fields.setdefault('is_superuser', True)
            if extra_fields.get('is_staff') is not True:
                raise ValueError('Superuser must have is_staff=True')
            if extra_fields.get('is_superuser') is not True:
                raise ValueError('Superuser must have is_superuser=True')
            return self._create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin): 
    """カスタムユーザーモデル"""
    initial_point = 50000
    email = models.EmailField("メールアドレス", unique=True) 
    point = models.PositiveIntegerField(default=initial_point)
    fav_products = models.ManyToManyField(Product, blank=True) 
    is_staff = models.BooleanField("is_staff", default=False) 
    is_active = models.BooleanField("is_active", default=True) 
    date_joined = models.DateTimeField("date_joined",default=timezone.now)

    objects = UserManager()

    USERNAME_FIELD = "email"
    EMAIL_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "user"
        verbose_name_plural = "users"

app/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class CustomUserCreationForm(UserCreationForm):
    class Meta:
       model = get_user_model()
       fields = ('email',)

app/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect # 追加
from django.contrib.auth import authenticate, login
from .forms import CustomUserCreationForm
from django.shortcuts import get_object_or_404, render, redirect 
from .models import Product
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST


def index(request):
    products = Product.objects.all().order_by('-id')
    return render(request, 'app/index.html', {'products': products})
def signup(request):
    if request.method == 'POST':
       form = CustomUserCreationForm(request.POST)
       if form.is_valid():
           new_user = form.save()
           input_email = form.cleaned_data['email']
           input_password = form.cleaned_data['password1']
           new_user = authenticate(email=input_email,
password=input_password)
           if new_user is not None:
               login(request, new_user)
               return redirect('app:index')
    else:
       form = CustomUserCreationForm()
    return render(request, 'app/signup.html', {'form': form})

def detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    context = {
       'product': product,
    }
    return render(request, 'app/detail.html', context)

@login_required

def fav_products(request):
    user = request.user
    products = user.fav_products.all()
    return render(request, 'app/index.html', {'products': products})
    
@require_POST
def toggle_fav_product_status(request):
    product = get_object_or_404(Product, pk=request.POST["product_id"])
    user = request.user
    if product in user.fav_products.all():
       user.fav_products.remove(product)
    else:
       user.fav_products.add(product)
    return redirect('app:detail', product_id=product.id)

users/views.py
from django.shortcuts import render

# Create your views here.

app/templates/app/base.html
{% load static %}
{% load humanize %}

<!DOCTYPE html>
<html>
<head>
    <title>Djamazon</title>
    <link rel="stylesheet" type="text/css" href="{% static
'css/style.css' %}">
</head>
<body>
    <header>
       <div class="container">
           <h1><a href="{% url 'app:index' %}">Djamazon</a></h1>
           <div class="header-menu">

               {% if request.user.is_authenticated %}
               <span>Point: {{ user.point | intcomma }}</span>
               <span><a href="{% url 'app:fav_products' %}">お気に入り</a></span> 
               <span><a href="">カート</a></span>
                  <span><a href="">注文履歴</a></span>
                  <span><a href="{% url 'app:logout' %}">ログアウト</a></span>
               {% else %}
                  <span><a href="{% url 'app:login' %}">ログイン</a></span>
                  <span><a href="{% url 'app:signup' %}">新規登録</a></span>
               {% endif %}
           </div>
       </div>
    </header>
    <div class="container">
       {% for message in messages %}
           <p class="message-{{ message.tags }}">{{ message }}</p>
       {% endfor %}
       {% block content %}{% endblock %}
    </div>
</body>
</html>

app/templates/app/detail.html
{% extends 'app/base.html' %}
{% load humanize %}
{% block content %}
<div class="product-detail">
  <div class="product-detail-image">
    <img src="{{ product.image.url }}" class="product-img">
  </div>
</div>>

  <div class="product-detail-info">
    <h2>{{ product.name }}</h2>
    <hr>
  <div class="point-fav-section">
    <h4>{{ product.price | intcomma }}ポイント</h4> 
    {% if request.user.is_authenticated %}
      <form action="{% url 'app:toggle_fav_product_status' %}"
method="post">{% csrf_token %}
          <input type="hidden" name="product_id"
value="{{ product.id }}">
        {% if product in user.fav_products.all %}
          <input type="submit" name="submit" class="fav_button" value="
お気に入りから外す" /> 
        {% else %}
          <input type="submit" name="submit" class="fav_button" value=" お気に入りに入れる" />
        {% endif %}
      </form>
    {% endif %}
  </div>
  <p>{{ product.description }}</p>
  </div>
{% endblock %}

app/templates/app/index.html
{% extends 'app/base.html' %}
{% load humanize %}
{% block content %}
{% if 'fav_products' in request.path %}
<div style="font-weight:bold; font-size: 28px; margin-bottom: 20px;">
お気に入り商品
</div>
{% endif %}
<div class="product-container">
{% for product in products %}
    <div class="product">
       <a href="{% url 'app:detail' product.id %}">
           <img src="{{ product.image.url }}" class="product-img">
       </a>
       <div class="product-info">
           <div class="product-name">{{ product.name }}</div>
           <div class="product-price">Point: {{ product.price |
intcomma }}</div>
       </div>
    </div>
{% endfor %}
</div>

{% endblock %}

app/templates/app/login.html
{% extends 'app/base.html' %}
{% block content %}
<form class="form-signin" method="post">{% csrf_token %}
    {% if form.errors %}
<p>ユーザー名かパスワードが間違っています。</p> 
    {% endif %}
<h2>ログイン</h2>
<label>メールアドレス</label>
<input name="username"> <!-- email ではない --> 
<br>
<label>パスワード</label>
<input type="password" name="password">
<br>
<input type="submit" value="ログイン">

</form>
{% endblock %}

app/templates/signup.html
{% extends 'app/base.html' %}
{% block content %}
<h2>ユーザー登録</h2>
<form method="post" action="{% url 'app:signup' %}">
{% csrf_token %}
<label>メールアドレス</label> 
{{ form.email }}
{{ form.email.errors }} 
<br> 
<label>パスワード</label>
{{ form.password1 }}
{{ form.password1.errors }}
<br>
<label>パスワード(確認)</label>
{{ form.password2 }}
{{ form.password2.errors }}
<br>
<input type="submit" value="登録する">
</form>
{% endblock %}